/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    pages: Page;
    users: User;
    media: Media;
    icons: Icon;
    tags: Tag;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    icons: IconsSelect<false> | IconsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    Settings: Setting;
    navPrimary: NavPrimary;
    socialMediaLinks: SocialMediaLink;
    Footer: Footer;
  };
  globalsSelect: {
    Settings: SettingsSelect<false> | SettingsSelect<true>;
    navPrimary: NavPrimarySelect<false> | NavPrimarySelect<true>;
    socialMediaLinks: SocialMediaLinksSelect<false> | SocialMediaLinksSelect<true>;
    Footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title?: string | null;
  description?: string | null;
  featuredImageWithMetadata?: {
    featuredImage?: (string | null) | Media;
    caption?: string | null;
    credit?: string | null;
    creditLink?: string | null;
  };
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  tags?: (string | Tag)[] | null;
  relatedPosts?: (string | Post)[] | null;
  layout?:
    | (
        | {
            /**
             * Select the layout for this block
             */
            blockLayoutField?: ('default' | 'wide' | 'full') | null;
            codeBlockCode: string;
            codeBlockLabel?: string | null;
            codeBlockLanguage:
              | 'cpp'
              | 'css'
              | 'dockerfile'
              | 'html'
              | 'javascript'
              | 'json'
              | 'markdown'
              | 'php'
              | 'python'
              | 'ruby'
              | 'scss'
              | 'shell'
              | 'sql'
              | 'typescript'
              | 'xml'
              | 'yaml';
            hideHeader?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'code';
          }
        | {
            /**
             * Select the layout for this block
             */
            blockLayoutField?: ('default' | 'wide' | 'full') | null;
            heroBlockTitle: string;
            heroBlockSubtitle: string;
            heroBlockDescription: string;
            heroBlockButtonText: string;
            heroBlockButtonLink: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Select the layout for this block
             */
            blockLayoutField?: ('default' | 'wide' | 'full') | null;
            proseEditor: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'prose';
          }
        | {
            /**
             * Select the layout for this block
             */
            blockLayoutField?: ('default' | 'wide' | 'full') | null;
            image: string | Media;
            caption?: string | null;
            credit?: string | null;
            creditLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bigImage';
          }
        | {
            /**
             * Select the layout for this block
             */
            blockLayoutField?: ('default' | 'wide' | 'full') | null;
            informationBoxTitle?: string | null;
            informationBoxSubtitle?: string | null;
            informationBoxContent?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'informationBox';
          }
        | {
            /**
             * Select the layout for this block
             */
            blockLayoutField?: ('default' | 'wide' | 'full') | null;
            gridListBlockTitle?: string | null;
            gridListBlockDescription?: string | null;
            gridListBlockList?:
              | {
                  gridListBlockItemImage?: (string | null) | Icon;
                  gridListBlockItemTitle?: string | null;
                  gridListBlockItemDescription?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gridList';
          }
        | {
            /**
             * Select the layout for this block
             */
            blockLayoutField?: ('default' | 'wide' | 'full') | null;
            videoEmbedURL?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoEmbed';
          }
      )[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  _key?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      _key?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      _key?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      _key?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icons".
 */
export interface Icon {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title?: string | null;
  description?: string | null;
  featuredImage?: (string | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  layout?:
    | (
        | {
            /**
             * Select the layout for this block
             */
            blockLayoutField?: ('default' | 'wide' | 'full') | null;
            codeBlockCode: string;
            codeBlockLabel?: string | null;
            codeBlockLanguage:
              | 'cpp'
              | 'css'
              | 'dockerfile'
              | 'html'
              | 'javascript'
              | 'json'
              | 'markdown'
              | 'php'
              | 'python'
              | 'ruby'
              | 'scss'
              | 'shell'
              | 'sql'
              | 'typescript'
              | 'xml'
              | 'yaml';
            hideHeader?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'code';
          }
        | {
            /**
             * Select the layout for this block
             */
            blockLayoutField?: ('default' | 'wide' | 'full') | null;
            heroBlockTitle: string;
            heroBlockSubtitle: string;
            heroBlockDescription: string;
            heroBlockButtonText: string;
            heroBlockButtonLink: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Select the layout for this block
             */
            blockLayoutField?: ('default' | 'wide' | 'full') | null;
            proseEditor: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'prose';
          }
        | {
            /**
             * Select the layout for this block
             */
            blockLayoutField?: ('default' | 'wide' | 'full') | null;
            image: string | Media;
            caption?: string | null;
            credit?: string | null;
            creditLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bigImage';
          }
        | {
            /**
             * Select the layout for this block
             */
            blockLayoutField?: ('default' | 'wide' | 'full') | null;
            informationBoxTitle?: string | null;
            informationBoxSubtitle?: string | null;
            informationBoxContent?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'informationBox';
          }
        | {
            /**
             * Select the layout for this block
             */
            blockLayoutField?: ('default' | 'wide' | 'full') | null;
            gridListBlockTitle?: string | null;
            gridListBlockDescription?: string | null;
            gridListBlockList?:
              | {
                  gridListBlockItemImage?: (string | null) | Icon;
                  gridListBlockItemTitle?: string | null;
                  gridListBlockItemDescription?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gridList';
          }
      )[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'icons';
        value: string | Icon;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: string | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  featuredImageWithMetadata?:
    | T
    | {
        featuredImage?: T;
        caption?: T;
        credit?: T;
        creditLink?: T;
      };
  content?: T;
  tags?: T;
  relatedPosts?: T;
  layout?:
    | T
    | {
        code?:
          | T
          | {
              blockLayoutField?: T;
              codeBlockCode?: T;
              codeBlockLabel?: T;
              codeBlockLanguage?: T;
              hideHeader?: T;
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              blockLayoutField?: T;
              heroBlockTitle?: T;
              heroBlockSubtitle?: T;
              heroBlockDescription?: T;
              heroBlockButtonText?: T;
              heroBlockButtonLink?: T;
              id?: T;
              blockName?: T;
            };
        prose?:
          | T
          | {
              blockLayoutField?: T;
              proseEditor?: T;
              id?: T;
              blockName?: T;
            };
        bigImage?:
          | T
          | {
              blockLayoutField?: T;
              image?: T;
              caption?: T;
              credit?: T;
              creditLink?: T;
              id?: T;
              blockName?: T;
            };
        informationBox?:
          | T
          | {
              blockLayoutField?: T;
              informationBoxTitle?: T;
              informationBoxSubtitle?: T;
              informationBoxContent?: T;
              id?: T;
              blockName?: T;
            };
        gridList?:
          | T
          | {
              blockLayoutField?: T;
              gridListBlockTitle?: T;
              gridListBlockDescription?: T;
              gridListBlockList?:
                | T
                | {
                    gridListBlockItemImage?: T;
                    gridListBlockItemTitle?: T;
                    gridListBlockItemDescription?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        videoEmbed?:
          | T
          | {
              blockLayoutField?: T;
              videoEmbedURL?: T;
              id?: T;
              blockName?: T;
            };
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  featuredImage?: T;
  content?: T;
  layout?:
    | T
    | {
        code?:
          | T
          | {
              blockLayoutField?: T;
              codeBlockCode?: T;
              codeBlockLabel?: T;
              codeBlockLanguage?: T;
              hideHeader?: T;
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              blockLayoutField?: T;
              heroBlockTitle?: T;
              heroBlockSubtitle?: T;
              heroBlockDescription?: T;
              heroBlockButtonText?: T;
              heroBlockButtonLink?: T;
              id?: T;
              blockName?: T;
            };
        prose?:
          | T
          | {
              blockLayoutField?: T;
              proseEditor?: T;
              id?: T;
              blockName?: T;
            };
        bigImage?:
          | T
          | {
              blockLayoutField?: T;
              image?: T;
              caption?: T;
              credit?: T;
              creditLink?: T;
              id?: T;
              blockName?: T;
            };
        informationBox?:
          | T
          | {
              blockLayoutField?: T;
              informationBoxTitle?: T;
              informationBoxSubtitle?: T;
              informationBoxContent?: T;
              id?: T;
              blockName?: T;
            };
        gridList?:
          | T
          | {
              blockLayoutField?: T;
              gridListBlockTitle?: T;
              gridListBlockDescription?: T;
              gridListBlockList?:
                | T
                | {
                    gridListBlockItemImage?: T;
                    gridListBlockItemTitle?: T;
                    gridListBlockItemDescription?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _key?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              _key?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              _key?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              _key?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icons_select".
 */
export interface IconsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Settings".
 */
export interface Setting {
  id: string;
  /**
   * The Site title is used in the page meta title and can also be used to display the site title in the header, footer or anywhere else within the site.
   */
  siteTitle?: string | null;
  /**
   * Add some text that is typically used in the footer of the site to indicate copyright. If you wish to include the date it is recommended to do this in code, not typed here.
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navPrimary".
 */
export interface NavPrimary {
  id: string;
  items: {
    page: string | Page;
    id?: string | null;
  }[];
  socialLinks?:
    | {
        link: string;
        label: string;
        icon?: (string | null) | Icon;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socialMediaLinks".
 */
export interface SocialMediaLink {
  id: string;
  items: {
    name?: string | null;
    link?: string | null;
    'icon '?: (string | null) | Media;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Footer".
 */
export interface Footer {
  id: string;
  footerContactTitle?: string | null;
  footerContactEmail?: string | null;
  footerSocialTitle?: string | null;
  footerSocialLinksList?:
    | {
        footerSocialTitle?: string | null;
        footerSocialLink?: string | null;
        id?: string | null;
      }[]
    | null;
  footerToolsTitle?: string | null;
  footerToolsList?:
    | {
        footerToolsTitle?: string | null;
        footerToolsLink?: string | null;
        footerToolsIcon?: (string | null) | Icon;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navPrimary_select".
 */
export interface NavPrimarySelect<T extends boolean = true> {
  items?:
    | T
    | {
        page?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        link?: T;
        label?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socialMediaLinks_select".
 */
export interface SocialMediaLinksSelect<T extends boolean = true> {
  items?:
    | T
    | {
        name?: T;
        link?: T;
        'icon '?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  footerContactTitle?: T;
  footerContactEmail?: T;
  footerSocialTitle?: T;
  footerSocialLinksList?:
    | T
    | {
        footerSocialTitle?: T;
        footerSocialLink?: T;
        id?: T;
      };
  footerToolsTitle?: T;
  footerToolsList?:
    | T
    | {
        footerToolsTitle?: T;
        footerToolsLink?: T;
        footerToolsIcon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null)
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}